language: ruby
language: perl
os: osx
osx_image: xcode9.1
rvm: system

before_install:
  - brew update || brew update
  - export HOMEBREW_DEVELOPER="1"
  - brew install cpanm
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm URI::Escape
install:
  - brew tap KDE-mac/kde file://$PWD
script:
  - CHANGED_FILES=`git diff --name-only $TRAVIS_COMMIT_RANGE`
  - echo $CHANGED_FILES
  - tools/travis-ci.sh $CHANGED_FILES
