language: ruby
os: osx
rvm: system

before_install:
  - brew update || brew update
  - export HOMEBREW_DEVELOPER="1"
install:
  - brew tap KDE-mac/kde file://$PWD
script:
  - brew install KDE-mac/kde/kf5-karchive
